export default [
  {
    // background image
    image: 'img/rps3.png',
    // button's names
    names: ['Paper', 'Scissors', 'Rock'],
    // size of choice button
    size: 138,
    // array with [left, top] of all choice buttons
    coords: [
      [353, 52],
      [10, 52],
      [186, 347],
    ],
    // rules text
    rules: [
      'Paper beats rock',
      'Scissors beats a paper',
      'Rock beats scissors',
      'Make the right choice (images are also clickable) and win',
    ],
  },
  {
    image: 'img/rps5.jpg',
    names: ['Rock', 'Spock', 'Paper', 'Lizard', 'Scissors'],
    size: 138,
    coords: [
      [0, 139],
      [272, 332],
      [160, -18],
      [98, 339],
      [356, 127],
    ],
    rules: [
      'Rock beats scissors and lizard',
      'Spock beats rock and scissors',
      'Paper beats Spock and rock',
      'Lizard beats paper and Spock',
      'Scissors beats a lizard and paper',
      'Make the right choice (images are also clickable) and win',
    ],
  },
  {
    image: 'img/rps15.jpg',
    size: 65,
    coords: [
      [171, 20],
      [253, 19],
      [330, 53],
      [385, 115],
      [412, 193],
      [402, 276],
      [361, 348],
      [294, 398],
      [213, 415],
      [131, 398],
      [64, 348],
      [23, 276],
      [14, 194],
      [39, 114],
      [95, 53],
    ],
    names: [
      'Rock',
      'Gun',
      'Lighting',
      'Devil',
      'Dragon',
      'Water',
      'Air',
      'Paper',
      'Sponge',
      'Wolf',
      'Tree',
      'Human',
      'Snake',
      'Scissors',
      'Fire',
    ],
    rules: [
      'Rock beats fire, scissors, snake, human, tree, wolf, sponge',
      'Gun beats rock, fire, scissors, snake, human, tree, wolf',
      'Lighting beats gun, rock, fire, scissors, snake, human, tree',
      'Devil beats lighting, gun, rock, fire, scissors, snake, human',
      'Dragon beats devil, lighting, gun, rock, fire, scissors, snake',
      'Water beats dragon, devil, lighting, gun, rock, fire, scissors',
      'Air beats water, dragon, devil, lighting, gun, rock, fire',
      'Paper beats air, water, dragon, devil, lighting, gun, rock',
      'Sponge beats paper, air, water, dragon, devil, lighting, gun',
      'Wolf beats sponge, paper, air, water, dragon, devil, lighting',
      'Tree beats wolf, sponge, paper, air, water, dragon, devil',
      'Human beats tree, wolf, sponge, paper, air, water, dragon',
      'Snake beats human, tree, wolf, sponge, paper, air, water',
      'Scissors beats snake, human, tree, wolf, sponge, paper, air',
      'Fire beats scissors, snake, human, tree, wolf, sponge, paper',
      'Make the right choice (images are also clickable) and win',
    ],
  },
];
